<?php
/**
* @var $block \Magenest\CustomSession\Block\Adminhtml\Order\View\Tab\CustomTab
*/
?>

<div class="fieldset-wrapper order-information">
   <div>
       <h2>Datos de Facturación</h2>
   </div>
   <div class="fieldset-wrapper-title">
       <span class="title"><?php /* @escapeNotVerified */
           echo __('Información de facturación') ?></span>
   </div>
   <table class="admin__table-secondary">
       <tbody>
       <?php echo $block->getChildHtml(); ?>
       <tr>
           <th><?php /* @escapeNotVerified */
               echo __('Order ID:') ?></th>
           <td><?php echo $block->getOrderIncrementId(); ?></td>
       </tr>
       <tr>
           <th><?php /* @escapeNotVerified */
               echo __('¿Requiere Factura?') ?></th>
           <td><?php echo $block->getOrderFactura(); ?></td>
       </tr>
       <tr>
           <th><?php /* @escapeNotVerified */
               echo __('RFC') ?></th>
           <td><?php echo $block->getOrderRFC(); ?></td>
       </tr>
       <tr>
           <th><?php /* @escapeNotVerified */
               echo __('Razón Social') ?></th>
           <td><?php echo $block->getOrderCompany(); ?></td>
       </tr>
       </tbody>
   </table>
</div>